title: Ad_config Table
description: OS X Active Directory configuration.
platform: macos
log_source: osquery
event_code: ad_config
event_version: 4.4.2
event_fields:
- standard_name: TBD
  standard_type: TBD
  name: name
  type: TEXT
  description: The OS X-specific configuration name
  sample_value: TBD
- standard_name: TBD
  standard_type: TBD
  name: domain
  type: TEXT
  description: Active Directory trust domain
  sample_value: TBD
- standard_name: TBD
  standard_type: TBD
  name: option
  type: TEXT
  description: Canonical name of option
  sample_value: TBD
- standard_name: TBD
  standard_type: TBD
  name: value
  type: TEXT
  description: Variable typed option value
  sample_value: TBD
references:
- text: OSQuery table documentation
  link: https://osquery.io/schema/current#ad_config
tags: []
