title: Sip_config Table
description: Apple's System Integrity Protection (rootless) status.
platform: macos
log_source: osquery
event_code: sip_config
event_version: 4.4.2
event_fields:
- standard_name: TBD
  standard_type: TBD
  name: config_flag
  type: TEXT
  description: The System Integrity Protection config flag
  sample_value: TBD
- standard_name: TBD
  standard_type: TBD
  name: enabled
  type: INTEGER
  description: 1 if this configuration is enabled, otherwise 0
  sample_value: TBD
- standard_name: TBD
  standard_type: TBD
  name: enabled_nvram
  type: INTEGER
  description: 1 if this configuration is enabled, otherwise 0
  sample_value: TBD
references:
- text: OSQuery table documentation
  link: https://osquery.io/schema/current#sip_config
tags: []
