title: Default_environment Table
description: Default environment variables and values.
platform: windows
log_source: osquery
event_code: default_environment
event_version: 4.4.2
event_fields:
- standard_name: TBD
  standard_type: TBD
  name: variable
  type: TEXT
  description: Name of the environment variable
  sample_value: TBD
- standard_name: TBD
  standard_type: TBD
  name: value
  type: TEXT
  description: Value of the environment variable
  sample_value: TBD
- standard_name: TBD
  standard_type: TBD
  name: expand
  type: INTEGER
  description: 1 if the variable needs expanding, 0 otherwise
  sample_value: TBD
references:
- text: OSQuery table documentation
  link: https://osquery.io/schema/current#default_environment
tags: []
