title: Services Table
description: Lists all installed Windows services and their relevant data.
platform: windows
log_source: osquery
event_code: services
event_version: 4.4.2
event_fields:
- standard_name: service_name
  standard_type: TBD
  name: name
  type: TEXT
  description: Service name
  sample_value: TBD
- standard_name: service_type
  standard_type: TBD
  name: service_type
  type: TEXT
  description: 'Service Type: OWN_PROCESS, SHARE_PROCESS and maybe Interactive (can
    interact with the desktop)'
  sample_value: TBD
- standard_name: service_display_name
  standard_type: TBD
  name: display_name
  type: TEXT
  description: Service Display name
  sample_value: TBD
- standard_name: service_status
  standard_type: TBD
  name: status
  type: TEXT
  description: 'Service Current status: STOPPED, START_PENDING, STOP_PENDING, RUNNING,
    CONTINUE_PENDING, PAUSE_PENDING, PAUSED'
  sample_value: TBD
- standard_name: process_id
  standard_type: TBD
  name: pid
  type: INTEGER
  description: the Process ID of the service
  sample_value: TBD
- standard_name: service_start_type
  standard_type: TBD
  name: start_type
  type: TEXT
  description: 'Service start type: BOOT_START, SYSTEM_START, AUTO_START, DEMAND_START,
    DISABLED'
  sample_value: TBD
- standard_name: service_error_code
  standard_type: TBD
  name: win32_exit_code
  type: INTEGER
  description: The error code that the service uses to report an error that occurs
    when it is starting or stopping
  sample_value: TBD
- standard_name: service_exit_code
  standard_type: TBD
  name: service_exit_code
  type: INTEGER
  description: The service-specific error code that the service returns when an error
    occurs while the service is starting or stopping
  sample_value: TBD
- standard_name: file_path
  standard_type: TBD
  name: path
  type: TEXT
  description: Path to Service Executable
  sample_value: TBD
- standard_name: module_path
  standard_type: TBD
  name: module_path
  type: TEXT
  description: Path to ServiceDll
  sample_value: TBD
- standard_name: service_description
  standard_type: TBD
  name: description
  type: TEXT
  description: Service Description
  sample_value: TBD
- standard_name: user_name
  standard_type: TBD
  name: user_account
  type: TEXT
  description: The name of the account that the service process will be logged on
    as when it runs. This name can be of the form Domain\\UserName. If the account
    belongs to the built-in domain, the name can be of the form .\\UserName.
  sample_value: TBD
references:
- text: OSQuery table documentation
  link: https://osquery.io/schema/current#services
tags: []
